yatube/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'
urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='groups'),
    path('', views.index, name='main'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('group/slug:slug', include('posts.urls', namespace='groups')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
        related_name='posts'
    )

    class Meta:
        ordering: tuple = ('-pub_date',)

    def __str__(self):
        return self.group.title

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Group, Post


POSTS_ON_VIEW: int = 10


def index(request):
    template = 'posts/index.html'
    posts = Post.objects.all()[:POSTS_ON_VIEW]
    title = 'Последние обновления на сайте'
    context = {
        'posts': posts,
        'title': title,
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    title = f'Записи сообщества {group.title}'
    posts = group.posts.order_by('-pub_date')[:POSTS_ON_VIEW]
    context = {
        'group': group,
        'posts': posts,
        'title': title,
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static "img/fav/fav.ico" %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "img/fav/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "img/fav/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "img/fav/favicon-16x16.png" %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <title>{{ title }}</title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<!DOCTYPE html>
{% load static %}
<!-- templates/icludes/footer.html -->
<html>
  <body>
    <footer class="border-top text-center py-3">
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>
    </footer>
  </body>
</html>

yatube/templates/includes/header.html
<!DOCTYPE html>
<!-- templates/icludes/header.html -->
{% load static %}
<html>
  <body>
    <header>
      <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'posts:main' %}">
            <img src="{% static "img/logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Yatube</span>
          </a>
        </div>
      </nav>
    </header>
  </body>
</html>

yatube/templates/posts/group_list.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% extends 'base.html' %}
{% load static %}
<html lang="ru"> <!-- Язык сайта - русский -->
  <body>
    <main>
      {%block content%}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h1>Записи группы {{ group|title }}</h1>
        {% for post in posts %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>{{ post.text }}</p>
          <a href="/group/{{ group.slug }}">все записи группы</a>
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        <!-- под последним постом нет линии -->
      </div>
      {%endblock%}
    </main>
  </body>
</html>

yatube/templates/posts/index.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% extends 'base.html' %}
{% load static %}
<html lang="ru"> <!-- Язык сайта - русский -->
  <body>
    <main>
      {%block content%}
      <title>{{ title }}</title>
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h1>{{ index_header }}</h1>
      {% for post in posts %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          <li>
            Группа: {{ post.group.title }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
        {% if post.group %}
          <a href="/group/{{ post.group.slug }}">все записи группы</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
        <!-- под последним постом нет линии -->
      </div>
      {%endblock%}
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->
  </body>
</html>